version: "3.9"

services:
  # exchange:
  #   build: './exchange'
  #   ports: 
  #     - "9000:9000"
  users:
    build: './users'
    ports: 
      - "9001:9001"
    volumes:
      - ./users:/app
    tty: true
    stdin_open: true
    depends_on:
      - usersdb
  usersdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - '.env'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  # api:
  #   build: './api'
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./api:/app
volumes:
  mysql-data:

